<?php

namespace App\Domains\Reporting;

use App\Domains\Reporting\Contracts\ReportGenerator;
use App\Domains\Reporting\Reports\ActiveMasterDataReport;
use App\Domains\Reporting\Reports\AutoGeneratedDocumentReport;
use App\Domains\Reporting\Reports\BatchRecordSummaryReport;
use App\Domains\Reporting\Reports\Wm001LabScalesCalibrationReport;
use App\Domains\Reporting\Reports\Wm002SaltMeterCalibrationReport;
use App\Domains\Reporting\Reports\Wm006ViscosityAutozeroReport;
use App\Domains\Reporting\Reports\Wm013ProductionScalesCalibrationReport;
use App\Domains\Reporting\Reports\DailyIntermediateProductionReport;
use App\Domains\Reporting\Reports\DailyProductionSummaryReport;
use App\Domains\Reporting\Reports\DrumProcessingSummaryReport;
use App\Domains\Reporting\Reports\MetalDetectorVerificationSheetReport;
use App\Domains\Reporting\Reports\OpenBatchesReport;
use App\Domains\Reporting\Reports\OverdueMetalDetectorReport;
use App\Domains\Reporting\Reports\ProgramDocumentReport;
use App\Domains\Reporting\Reports\RecipeBatchCardReport;
use App\Domains\Reporting\Reports\PackingWeightExceptionsReport;
use App\Domains\Reporting\Reports\QaApprovalQueueReport;
use App\Domains\Reporting\Reports\TraceabilityExceptionsReport;
use App\Domains\Reporting\Reports\Wm005WetMustardLabTestingReport;
use App\Domains\Reporting\Reports\Wm010RinseWaterTestReport;
use App\Domains\Reporting\Support\DocumentSources;
use App\Models\DocumentReference;

/**
 * Registry of whitelisted DBMTS report generators. Report keys must be
 * registered here before manual or scheduled execution (scope §11 validation).
 */
class ReportRegistry
{
    /**
     * @var array<string, class-string<ReportGenerator>>
     */
    private array $map = [
        DailyProductionSummaryReport::KEY => DailyProductionSummaryReport::class,
        DailyIntermediateProductionReport::KEY => DailyIntermediateProductionReport::class,
        MetalDetectorVerificationSheetReport::KEY => MetalDetectorVerificationSheetReport::class,
        OpenBatchesReport::KEY => OpenBatchesReport::class,
        OverdueMetalDetectorReport::KEY => OverdueMetalDetectorReport::class,
        PackingWeightExceptionsReport::KEY => PackingWeightExceptionsReport::class,
        DrumProcessingSummaryReport::KEY => DrumProcessingSummaryReport::class,
        QaApprovalQueueReport::KEY => QaApprovalQueueReport::class,
        TraceabilityExceptionsReport::KEY => TraceabilityExceptionsReport::class,
        ActiveMasterDataReport::KEY => ActiveMasterDataReport::class,
        BatchRecordSummaryReport::KEY => BatchRecordSummaryReport::class,
        Wm001LabScalesCalibrationReport::KEY => Wm001LabScalesCalibrationReport::class,
        Wm002SaltMeterCalibrationReport::KEY => Wm002SaltMeterCalibrationReport::class,
        Wm006ViscosityAutozeroReport::KEY => Wm006ViscosityAutozeroReport::class,
        Wm013ProductionScalesCalibrationReport::KEY => Wm013ProductionScalesCalibrationReport::class,
        Wm005WetMustardLabTestingReport::KEY => Wm005WetMustardLabTestingReport::class,
        Wm010RinseWaterTestReport::KEY => Wm010RinseWaterTestReport::class,
    ];

    /**
     * Prefix used for dynamic, per-DocumentReference report keys (e.g.
     * "doc_WM012"), configured in Settings > Documents: material-triggered
     * documents and documents linked to a table-backed program.
     */
    private const DOCUMENT_KEY_PREFIX = 'doc_';

    public function has(string $key): bool
    {
        return isset($this->map[$key]) || $this->resolveDocumentReport($key) !== null;
    }

    public function get(string $key): ?ReportGenerator
    {
        if (isset($this->map[$key])) {
            return app($this->map[$key]);
        }

        return $this->resolveDocumentReport($key);
    }

    /**
     * @return array<int, string>
     */
    public function keys(): array
    {
        return array_keys($this->map);
    }

    private function resolveDocumentReport(string $key): ?ReportGenerator
    {
        if (! str_starts_with($key, self::DOCUMENT_KEY_PREFIX)) {
            return null;
        }

        // "doc_{code}@{MO}" is one run (MO) of a document that splits into runs.
        [$code, $run] = array_pad(explode(RecipeBatchCardReport::RUN_SEPARATOR, substr($key, strlen(self::DOCUMENT_KEY_PREFIX)), 2), 2, null);

        $document = DocumentReference::query()->where('code', $code)->first();
        if ($document === null) {
            return null;
        }

        $sources = app(DocumentSources::class);
        $link = $sources->linkFor($document);

        if ($link['type'] === DocumentSources::TYPE_RECIPE) {
            return new RecipeBatchCardReport($document, (string) $link['recipe_code'], $run !== null && $run !== '' ? $run : null);
        }

        if ($run !== null) {
            return null;
        }

        if ($link['type'] === DocumentSources::TYPE_MATERIAL_TRIGGER) {
            return empty($document->trigger_material_codes) ? null : new AutoGeneratedDocumentReport($document);
        }

        if ($link['type'] === DocumentSources::TYPE_PROGRAM && $sources->isTableBacked($link['program_key'])) {
            return new ProgramDocumentReport($document, $link['program_key']);
        }

        return null;
    }
}
