<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * WM003 is now an auto-generated document (Settings > Documents trigger material
 * codes -> AutoGeneratedDocumentReport, same as WM014/WM015 packaging docs) instead
 * of a manual entry screen, so the manual entries table is no longer needed.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::dropIfExists('wm003_ibc_traceability_entries');
    }

    public function down(): void
    {
        Schema::create('wm003_ibc_traceability_entries', function (Blueprint $table): void {
            $table->id();
            $table->date('date_used')->index();
            $table->date('supplier_production_date')->nullable();
            $table->date('best_before_date')->nullable();
            $table->string('batch_no', 120)->nullable();
            $table->time('time_on')->nullable();
            $table->string('operator_name');
            $table->foreignId('recorded_by_user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
        });
    }
};
