<?php

namespace App\Domains\Reporting\Support;

use App\Models\DocumentReference;
use App\Models\LabScaleCalibration;
use App\Models\ManufacturingOrder;
use App\Models\MetalDetectorCheck;
use App\Models\ProductionScaleCalibration;
use App\Models\SaltMeterCalibration;
use App\Models\ViscosityMeterAutozeroCheck;
use App\Models\WinManIssueLog;
use Carbon\CarbonInterface;
use Closure;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

/**
 * Registry of the data sources a controlled document can be linked to in
 * Settings > Documents, and the fields (columns) each source can print.
 *
 * A document is either "program driven" (filled from one of the app's
 * programs, e.g. the WM002 salt meter calibration screen) or "material
 * triggered" (generated when a configured raw material is issued to a batch).
 * The Columns editor, its preview and the generated PDFs all read the same
 * field definitions from here.
 *
 * Programs with a "model" entry are table-backed: their fields are discovered
 * from the model's table (types from its casts, foreign keys shown through
 * their BelongsTo relation) and they are generated by ProgramDocumentReport,
 * so adding one needs no other code.
 */
class DocumentSources
{
    /** Columns never offered as fields on table-backed programs. */
    private const HIDDEN_COLUMNS = ['id', 'created_at', 'updated_at', 'deleted_at', 'password', 'remember_token'];

    /** Attributes tried, in order, to display a related record. */
    private const DISPLAY_ATTRIBUTES = ['batch_number', 'mo_number', 'product_name', 'name', 'code', 'title'];

    /** @var array<string, array<int, array<string, mixed>>> */
    private array $discovered = [];

    public const TYPE_PROGRAM = 'program';

    public const TYPE_MATERIAL_TRIGGER = 'material_trigger';

    /** Explicitly not linked (stored so the code-prefix fallback no longer applies). */
    public const TYPE_NONE = 'none';

    /** Source key used for material-triggered documents (programs use their own keys). */
    public const MATERIAL_TRIGGER = 'material_trigger';

    private static ?bool $hasSourceColumns = null;

    /**
     * Programs a document can be linked to, keyed by program key.
     *
     * Table-backed programs also define: model, date_column (filters the report
     * period), and optionally scope (query constraint), labels, formats
     * ('headline'), hidden columns and default_columns (initially visible, in order).
     *
     * @return array<string, array<string, mixed>>
     */
    public function programs(): array
    {
        return [
            // Checks from the standalone Metal Detector Daily screen (not attached to a batch).
            'metal_detector_daily' => [
                'label' => 'Metal Detector Daily Verification',
                'code' => '',
                'configurable_pdf' => true,
                'instructions' => [],
                'model' => MetalDetectorCheck::class,
                'date_column' => 'check_time',
                'scope' => fn (Builder $query) => $query->whereNull('batch_record_id'),
                'hidden' => ['batch_record_id', 'manufacturing_order_id', 'product_id'],
                'default_columns' => ['check_time', 'check_type', 'fe10_pass', 'non_fe15_pass', 'ss20_pass', 'overall_result', 'signed_by'],
                'labels' => [
                    'check_time' => 'Date / Time',
                    'fe10_pass' => 'Ferrous 1.0',
                    'non_fe15_pass' => 'Non-Ferrous 1.5',
                    'ss20_pass' => 'SS 2.0',
                    'overall_result' => 'Result',
                    'is_recheck' => 'Re-check',
                    'signed_by' => 'Operator',
                ],
                'formats' => [
                    'check_type' => 'headline',
                    'overall_result' => 'headline',
                ],
                'samples' => [
                    'check_type' => 'Start Of Shift',
                    'failure_action' => '—',
                    'comments' => '—',
                ],
            ],
            'wm001_lab_scales' => [
                'label' => 'Lab Scales Daily Calibration',
                'code' => 'WM001',
                'configurable_pdf' => true,
                'instructions' => [
                    'Push and hold the Tare button until the display shows 0.00g.',
                    'Place the 100g weight on the scales bed.',
                    'Target: 100 +/- 0.02g. Out-of-spec results must be recorded with action.',
                ],
            ],
            'wm002_salt_meter' => [
                'label' => 'Daily Salt Meter Calibration',
                'code' => 'WM002',
                'configurable_pdf' => true,
                'instructions' => [
                    'Target reading is 100 +/- 2 mg/l.',
                    'If out of tolerance, check pipette, tip, and re-inject chloride solution before adjusting meter.',
                    'Inform QA if target cannot be achieved and record action taken.',
                ],
            ],
            'wm003_traceability' => [
                'label' => 'Raw Material Traceability',
                'code' => 'WM003',
                'configurable_pdf' => false,
                'instructions' => [],
            ],
            'wm004_pallecon' => [
                'label' => 'Pallecon Bulk Fill Traceability',
                'code' => 'WM004',
                'configurable_pdf' => false,
                'instructions' => [],
            ],
            'wm005_lab_testing' => [
                'label' => 'Wet Mustard Lab Testing',
                'code' => 'WM005',
                'configurable_pdf' => true,
                'instructions' => [],
            ],
            'wm006_viscosity_autozero' => [
                'label' => 'Viscosity Meter Autozero',
                'code' => 'WM006',
                'configurable_pdf' => true,
                'instructions' => [
                    'Follow instructions on COP WMUS004 to autozero viscosity meter.',
                    'If check is not complete, inform QA and record reason/action.',
                ],
            ],
            'wm010_rinse_water' => [
                'label' => 'Rinse Water Test',
                'code' => 'WM010',
                'configurable_pdf' => false,
                'instructions' => [],
            ],
            'wm013_production_scales' => [
                'label' => 'Production Scales Calibration',
                'code' => 'WM013',
                'configurable_pdf' => true,
                'instructions' => [
                    '100g weight should read 100 +/- 0.02g on powder 3kg scale.',
                    '10kg should read 10 +/- 0.1kg on powder 30kg and bucket filler scales.',
                    'Pallecon scale tolerance is 10 +/- 1kg.',
                    'Record out-of-spec actions and inform QA where needed.',
                ],
            ],
        ];
    }

    /**
     * Field definitions for a source key (a program key or MATERIAL_TRIGGER).
     *
     * @return array<int, array{key: string, label: string, width: float, visible: bool, sample: string, value: (Closure(mixed): string)|null}>
     */
    public function fields(?string $sourceKey): array
    {
        if ($this->isTableBacked($sourceKey)) {
            return $this->discovered[$sourceKey] ??= $this->discoverFields($sourceKey);
        }

        return match ($sourceKey) {
            'wm001_lab_scales' => $this->readingCalibrationFields(LabScaleCalibration::class),
            'wm002_salt_meter' => $this->readingCalibrationFields(SaltMeterCalibration::class),
            'wm003_traceability' => [
                $this->field('date_used', 'Date Used', 16, '2026-08-12'),
                $this->field('supplier_production_date', 'Supplier Production Date', 18, '2026-08-12'),
                $this->field('best_before_date', 'Best Before Date', 16, '2026-08-12'),
                $this->field('batch_no', 'Batch No.', 16, 'hqwidj'),
                $this->field('time_on', 'Time On', 12, '06:30'),
                $this->field('operator_name', 'Operator Name', 22, 'Adrian Lacki'),
            ],
            'wm004_pallecon' => [
                $this->field('mo_number', 'MO Number', 8, '1224'),
                $this->field('ticket_number', 'Ticket Number', 9, 'TK-10092'),
                $this->field('serial_number', 'Serial Number', 10, 'S0400332'),
                $this->field('top_seal_number', 'Top Seal Number', 8, 'TS8821'),
                $this->field('bottom_seal_number', 'Bottom Seal Number', 8, 'BS9912'),
                $this->field('liner_number', 'Liner Number', 7, 'LN-22'),
                $this->field('liner_batch_code', 'Liner Batch Code', 8, 'LBC-722A'),
                $this->field('fill_weight', 'Fill Weight', 7, '1000.000'),
                $this->field('start_time', 'Start Time', 8, '07:00'),
                $this->field('finish_time', 'Finish Time', 8, '07:55'),
                $this->field('checked_by', 'Checked By', 9, 'Operator QA'),
                $this->field('checked_at', 'Checked At', 8, '2026-08-12 08:00'),
            ],
            'wm005_lab_testing' => [
                $this->field('tested_date', 'Date', 6, '2026-08-12'),
                $this->field('tested_time', 'Time', 4, '06:30'),
                $this->field('mo_number', 'MO Number', 8, '1224'),
                $this->field('batch_number', 'Batch Number', 8, 'hqwidj'),
                $this->field('ph', 'pH', 10, '23.000'),
                $this->field('acidity_acetic', 'Acidity (as acetic)', 10, '32.000'),
                $this->field('acidity_citric', 'Acidity (as citric)', 5, '21.000'),
                $this->field('salt', 'Salt', 12, '23.000'),
                $this->field('viscosity_brookfield', 'Viscosity (Brookfield)', 11, '41.000'),
                $this->field('viscosity_bostwick', 'Viscosity (Bostwick)', 5, '12.000'),
                $this->field('aw', 'aW', 5, '12.000'),
                $this->field('solids', 'Solids', 10, '123.000'),
                $this->field('appearance', 'Appearance', 10, 'Pass'),
                $this->field('tested_by', 'Test by (Print name)', 11, 'Adrian Lacki'),
            ],
            'wm006_viscosity_autozero' => [
                $this->field('checked_date', 'Date', 18, '2026-08-12', fn (ViscosityMeterAutozeroCheck $row): string => $row->checked_date?->toDateString() ?? '—'),
                $this->field('complete', 'Complete Y/N', 14, 'Yes', fn (ViscosityMeterAutozeroCheck $row): string => $row->complete ? 'Yes' : 'No'),
                $this->field('operator_name', 'Operator Name', 26, 'Adrian Lacki', fn (ViscosityMeterAutozeroCheck $row): string => (string) $row->operator_name),
                $this->field('deviation_reason', 'Deviation / Action', 42, '—', fn (ViscosityMeterAutozeroCheck $row): string => (string) ($row->deviation_reason ?? '—')),
            ],
            'wm010_rinse_water' => [
                $this->field('section', 'Section', 18, 'Mixing'),
                $this->field('equipment', 'Equipment', 18, 'Vessel 1'),
                $this->field('reading', 'Reading', 12, '12.5 ppm'),
                $this->field('target', 'Target', 10, '< 20'),
                $this->field('result', 'Result', 10, 'OK'),
                $this->field('pass_or_fail', 'Pass / Fail', 10, 'Pass'),
                $this->field('action_taken_if_failed', 'Action if Failed', 12, '—'),
                $this->field('operator_name', 'Operator Name', 10, 'Adrian Lacki'),
            ],
            'wm013_production_scales' => [
                $this->field('checked_date', 'Date', 11, '2026-08-12', fn (ProductionScaleCalibration $row): string => $row->checked_date?->toDateString() ?? '—'),
                $this->field('powder_3kg_reading', 'Powder 3kg', 10, '100.010', fn (ProductionScaleCalibration $row): string => $this->decimal($row->powder_3kg_reading)),
                $this->field('powder_30kg_reading', 'Powder 30kg', 10, '10.020', fn (ProductionScaleCalibration $row): string => $this->decimal($row->powder_30kg_reading)),
                $this->field('pallecon_scale_reading', 'Pallecon', 10, '10.400', fn (ProductionScaleCalibration $row): string => $this->decimal($row->pallecon_scale_reading)),
                $this->field('bucket_filler_scale_reading', 'Bucket Filler', 10, '10.050', fn (ProductionScaleCalibration $row): string => $this->decimal($row->bucket_filler_scale_reading)),
                $this->field('passed', 'Pass/Fail', 9, 'Pass', fn (ProductionScaleCalibration $row): string => $row->passed ? 'Pass' : 'Fail'),
                $this->field('operator_name', 'Operator Name', 15, 'Adrian Lacki', fn (ProductionScaleCalibration $row): string => (string) $row->operator_name),
                $this->field('deviation_reason', 'Deviation / Action', 25, '—', fn (ProductionScaleCalibration $row): string => (string) ($row->deviation_reason ?? '—')),
            ],
            self::MATERIAL_TRIGGER => [
                $this->field('issue_date', 'Date/Time', 13, '2026-08-12 06:30', fn (WinManIssueLog $log): string => $log->issue_date?->format('Y-m-d H:i') ?? '—'),
                $this->field('batch_number', 'Batch', 12, 'WM-24113', fn (WinManIssueLog $log): string => (string) ($log->batchRecord?->batch_number ?? '—')),
                $this->field('mo_reference', 'MO Ref', 10, 'MO001224', fn (WinManIssueLog $log): string => $this->moReference($log)),
                $this->field('material_code', 'Material Code', 11, '90010012', fn (WinManIssueLog $log): string => (string) $log->material_code),
                $this->field('material_description', 'Material', 18, '5kg Bucket White', fn (WinManIssueLog $log): string => (string) ($log->batchIngredientLot?->material_description ?? '—')),
                $this->field('lot_number', 'Lot Number', 12, 'LOT-22841', fn (WinManIssueLog $log): string => (string) ($log->lot_number ?? '—')),
                $this->field('quantity_issued', 'Qty Issued (kg)', 11, '25.500', fn (WinManIssueLog $log): string => $this->decimal($log->quantity_issued)),
                $this->field('issue_user', 'Issued By', 13, 'Adrian Lacki', fn (WinManIssueLog $log): string => (string) ($log->issue_user ?? '—')),
            ],
            default => [],
        };
    }

    /**
     * Column settings (key/label/width/visible) used when a document has none saved.
     *
     * @return array<int, array{key: string, label: string, width: float, visible: bool}>
     */
    public function defaultColumns(?string $sourceKey): array
    {
        return array_map(
            fn (array $field): array => [
                'key' => $field['key'],
                'label' => $field['label'],
                'width' => $field['width'],
                'visible' => $field['visible'],
            ],
            $this->fields($sourceKey),
        );
    }

    /** @return array<int, string> */
    public function defaultInstructions(?string $sourceKey): array
    {
        return $this->programs()[$sourceKey]['instructions'] ?? [];
    }

    /**
     * Sample cell values for every known field key, used by the layout preview.
     *
     * @return array<string, string>
     */
    public function sampleValues(): array
    {
        $samples = [];
        foreach ([...array_keys($this->programs()), self::MATERIAL_TRIGGER] as $sourceKey) {
            foreach ($this->fields($sourceKey) as $field) {
                $samples[$field['key']] ??= $field['sample'];
            }
        }

        return $samples;
    }

    public function isProgram(?string $programKey): bool
    {
        return $programKey !== null && array_key_exists($programKey, $this->programs());
    }

    public function programKeyForCode(?string $documentCode): ?string
    {
        $code = strtoupper(trim((string) $documentCode));
        if ($code === '') {
            return null;
        }

        foreach ($this->programs() as $key => $program) {
            if ($program['code'] !== '' && str_starts_with($code, $program['code'])) {
                return $key;
            }
        }

        return null;
    }

    /**
     * The source type and program key a document is linked to. Documents saved
     * before linking existed fall back to: material trigger when trigger codes
     * are configured, otherwise the program whose code prefix matches.
     *
     * @return array{type: string|null, program_key: string|null}
     */
    public function linkFor(?DocumentReference $document, ?string $fallbackCode = null): array
    {
        $storedType = $document?->getAttribute('source_type');
        $storedProgram = $document?->getAttribute('program_key');

        if ($storedType === self::TYPE_MATERIAL_TRIGGER) {
            return ['type' => self::TYPE_MATERIAL_TRIGGER, 'program_key' => null];
        }

        if ($storedType === self::TYPE_PROGRAM && $this->isProgram($storedProgram)) {
            return ['type' => self::TYPE_PROGRAM, 'program_key' => $storedProgram];
        }

        if ($storedType === null && ! empty($document?->trigger_material_codes)) {
            return ['type' => self::TYPE_MATERIAL_TRIGGER, 'program_key' => null];
        }

        if ($storedType === null) {
            $programKey = $this->programKeyForCode($document?->code ?? $fallbackCode);
            if ($programKey !== null) {
                return ['type' => self::TYPE_PROGRAM, 'program_key' => $programKey];
            }
        }

        return ['type' => null, 'program_key' => null];
    }

    public function sourceKey(?string $type, ?string $programKey): ?string
    {
        return match ($type) {
            self::TYPE_MATERIAL_TRIGGER => self::MATERIAL_TRIGGER,
            self::TYPE_PROGRAM => $this->isProgram($programKey) ? $programKey : null,
            default => null,
        };
    }

    public function sourceKeyFor(?DocumentReference $document, ?string $fallbackCode = null): ?string
    {
        $link = $this->linkFor($document, $fallbackCode);

        return $this->sourceKey($link['type'], $link['program_key']);
    }

    /**
     * The document linked to a program: an explicit link wins, otherwise the
     * document whose code matches the program's code.
     */
    public function documentForProgram(string $programKey): ?DocumentReference
    {
        if ($this->hasSourceColumns()) {
            $linked = DocumentReference::query()
                ->where('source_type', self::TYPE_PROGRAM)
                ->where('program_key', $programKey)
                ->orderBy('code')
                ->first();

            if ($linked !== null) {
                return $linked;
            }
        }

        $code = $this->programs()[$programKey]['code'] ?? null;

        return $code !== null ? DocumentReference::query()->where('code', $code)->first() : null;
    }

    public function hasSourceColumns(): bool
    {
        if (self::$hasSourceColumns === null) {
            try {
                self::$hasSourceColumns = Schema::hasColumn('document_references', 'source_type');
            } catch (\Throwable) {
                return false;
            }
        }

        return self::$hasSourceColumns;
    }

    /** Whether the program's fields come from its table (and ProgramDocumentReport generates it). */
    public function isTableBacked(?string $sourceKey): bool
    {
        return isset($this->programs()[$sourceKey]['model']);
    }

    /**
     * Records of a table-backed program within the period, with the relations
     * its fields display eager loaded.
     *
     * @return iterable<int, Model>
     */
    public function records(string $programKey, CarbonInterface $from, CarbonInterface $to): iterable
    {
        if (! $this->isTableBacked($programKey)) {
            return [];
        }

        $program = $this->programs()[$programKey];
        $dateColumn = $program['date_column'];
        $relations = collect($this->fields($programKey))->pluck('relation')->filter()->unique()->values()->all();

        $query = $program['model']::query()
            ->with($relations)
            ->whereDate($dateColumn, '>=', $from->toDateString())
            ->whereDate($dateColumn, '<=', $to->toDateString())
            ->orderBy($dateColumn)
            ->orderBy('id');

        if (($program['scope'] ?? null) instanceof Closure) {
            $program['scope']($query);
        }

        return $query->get();
    }

    /**
     * Builds field definitions from a table-backed program's table columns.
     *
     * @return array<int, array<string, mixed>>
     */
    private function discoverFields(string $programKey): array
    {
        $program = $this->programs()[$programKey];
        /** @var Model $model */
        $model = new $program['model'];
        $casts = $model->getCasts();
        $hidden = [...self::HIDDEN_COLUMNS, ...($program['hidden'] ?? [])];
        $defaults = $program['default_columns'] ?? [];

        try {
            $columns = Schema::getColumnListing($model->getTable());
        } catch (\Throwable) {
            return [];
        }

        $fields = [];
        foreach ($columns as $column) {
            if (in_array($column, $hidden, true)) {
                continue;
            }

            $relation = $this->belongsToFor($model, $column);
            if ($relation === null && str_ends_with($column, '_id')) {
                continue; // a bare foreign key id means nothing on paper
            }

            [$value, $sample] = $relation !== null
                ? $this->relationFormatter($relation)
                : $this->columnFormatter($column, $casts[$column] ?? null, $program['formats'][$column] ?? null);

            $fields[$column] = [
                'key' => $column,
                'label' => $program['labels'][$column] ?? Str::headline(preg_replace('/_id$/', '', $column)),
                'width' => 8.0,
                'visible' => $defaults === [] || in_array($column, $defaults, true),
                'sample' => $program['samples'][$column] ?? $sample,
                'value' => $value,
                'relation' => $relation['method'] ?? null,
            ];
        }

        // Default columns first, in the order given, then the rest as they appear in the table (usort is stable).
        $ordered = array_values($fields);
        usort($ordered, fn (array $a, array $b): int => $this->defaultPosition($a['key'], $defaults) <=> $this->defaultPosition($b['key'], $defaults));

        $visibleCount = count(array_filter($ordered, fn (array $field): bool => $field['visible']));
        $share = $visibleCount > 0 ? floor(200 / $visibleCount) / 2 : 8.0;

        $remainder = $visibleCount > 0 ? 100 - ($share * $visibleCount) : 0;

        return array_map(function (array $field) use ($share, &$remainder): array {
            $field['width'] = $field['visible'] ? $share + $remainder : 8.0;
            if ($field['visible']) {
                $remainder = 0; // the first visible column absorbs the rounding so visible widths total 100
            }

            return $field;
        }, $ordered);
    }

    /** @param array<int, string> $defaults */
    private function defaultPosition(string $key, array $defaults): int
    {
        $position = array_search($key, $defaults, true);

        return $position === false ? PHP_INT_MAX : $position;
    }

    /** @return array{method: string, attribute: string}|null */
    private function belongsToFor(Model $model, string $column): ?array
    {
        $method = Str::camel(preg_replace('/_id$/', '', $column));
        if (! method_exists($model, $method)) {
            return null;
        }

        try {
            $relation = $model->{$method}();
        } catch (\Throwable) {
            return null;
        }

        if (! $relation instanceof BelongsTo || $relation->getForeignKeyName() !== $column) {
            return null;
        }

        try {
            $relatedColumns = Schema::getColumnListing($relation->getRelated()->getTable());
        } catch (\Throwable) {
            return null;
        }

        foreach (self::DISPLAY_ATTRIBUTES as $attribute) {
            if (in_array($attribute, $relatedColumns, true)) {
                return ['method' => $method, 'attribute' => $attribute];
            }
        }

        return null;
    }

    /**
     * @param  array{method: string, attribute: string}  $relation
     * @return array{0: Closure, 1: string}
     */
    private function relationFormatter(array $relation): array
    {
        $samples = [
            'batch_number' => 'WM-24113',
            'mo_number' => '1224',
            'product_name' => 'Wet Mustard 20kg',
            'name' => 'Adrian Lacki',
        ];

        return [
            fn (Model $record): string => (string) ($record->{$relation['method']}?->{$relation['attribute']} ?? '—'),
            $samples[$relation['attribute']] ?? 'Sample',
        ];
    }

    /** @return array{0: Closure, 1: string} */
    private function columnFormatter(string $column, ?string $cast, ?string $format): array
    {
        $cast = $cast !== null ? strtolower(explode(':', $cast)[0]) : null;

        return match (true) {
            $format === 'headline' => [
                fn (Model $record): string => filled($record->{$column}) ? Str::headline((string) $record->{$column}) : '—',
                'Pass',
            ],
            in_array($cast, ['bool', 'boolean'], true) && str_ends_with($column, '_pass') => [
                fn (Model $record): string => $record->{$column} === null ? '—' : ($record->{$column} ? 'Pass' : 'Fail'),
                'Pass',
            ],
            in_array($cast, ['bool', 'boolean'], true) => [
                fn (Model $record): string => $record->{$column} === null ? '—' : ($record->{$column} ? 'Yes' : 'No'),
                'Yes',
            ],
            in_array($cast, ['datetime', 'immutable_datetime'], true) => [
                fn (Model $record): string => $record->{$column}?->format('Y-m-d H:i') ?? '—',
                '2026-08-12 06:30',
            ],
            in_array($cast, ['date', 'immutable_date'], true) => [
                fn (Model $record): string => $record->{$column}?->toDateString() ?? '—',
                '2026-08-12',
            ],
            in_array($cast, ['decimal', 'float', 'double'], true) => [
                fn (Model $record): string => $this->decimal($record->{$column}),
                '12.000',
            ],
            default => [
                fn (Model $record): string => filled($record->{$column}) ? (string) $record->{$column} : '—',
                'Sample',
            ],
        };
    }

    /**
     * @param  class-string  $model
     * @return array<int, array<string, mixed>>
     */
    private function readingCalibrationFields(string $model): array
    {
        return [
            $this->field('checked_date', 'Date', 18, '2026-08-12', fn (LabScaleCalibration|SaltMeterCalibration $row): string => $row->checked_date?->toDateString() ?? '—'),
            $this->field('reading', $model === SaltMeterCalibration::class ? 'Reading (mg/l)' : 'Reading', 16, '100.010', fn (LabScaleCalibration|SaltMeterCalibration $row): string => $this->decimal($row->reading)),
            $this->field('passed', 'Pass/Fail', 12, 'Pass', fn (LabScaleCalibration|SaltMeterCalibration $row): string => $row->passed ? 'Pass' : 'Fail'),
            $this->field('operator_name', 'Operator Name', 22, 'Adrian Lacki', fn (LabScaleCalibration|SaltMeterCalibration $row): string => (string) $row->operator_name),
            $this->field('deviation_reason', 'Deviation / Action', 32, '—', fn (LabScaleCalibration|SaltMeterCalibration $row): string => (string) ($row->deviation_reason ?? '—')),
        ];
    }

    /** @return array{key: string, label: string, width: float, visible: bool, sample: string, value: Closure|null} */
    private function field(string $key, string $label, float $width, string $sample, ?Closure $value = null, bool $visible = true): array
    {
        return [
            'key' => $key,
            'label' => $label,
            'width' => $width,
            'visible' => $visible,
            'sample' => $sample,
            'value' => $value,
        ];
    }

    private function decimal(mixed $value): string
    {
        return $value === null ? '—' : number_format((float) $value, 3, '.', '');
    }

    private function moReference(WinManIssueLog $log): string
    {
        if ($log->winman_manufacturing_order === null) {
            return '—';
        }

        $moRef = ManufacturingOrder::query()
            ->where('winman_manufacturing_order', $log->winman_manufacturing_order)
            ->value('winman_manufacturing_order_id');

        return (string) ($moRef ?? $log->winman_manufacturing_order);
    }
}
