<?php

namespace App\Operations;

use App\Domains\Reporting\Contracts\SplitsIntoRuns;
use App\Domains\Reporting\Jobs\ResolveReportRecipientsJob;
use App\Domains\Reporting\ReportRegistry;
use App\Domains\Reporting\Reports\AutoGeneratedDocumentReport;
use App\Jobs\SendReportEmailJob;
use App\Models\ReportSendLog;
use App\Models\User;
use Carbon\CarbonInterface;
use Throwable;

/**
 * Generates a report, resolves its recipients, queues the Office 365 send and
 * always writes a send-log row (scope §14.7). Reused by manual Send Now and the
 * scheduled runner. The actual email delivery happens in the background
 * (SendReportEmailJob) so a manual "Send Now" click doesn't block on SMTP.
 */
class SendReportOperation
{
    public function __construct(
        private readonly ReportRegistry $registry,
        private readonly ResolveReportRecipientsJob $resolveRecipients,
    ) {
    }

    public function __invoke(
        string $reportKey,
        CarbonInterface $from,
        CarbonInterface $to,
        string $triggerMode,
        ?User $user = null,
    ): ReportSendLog {
        $log = ReportSendLog::create([
            'report_key' => $reportKey,
            'trigger_mode' => $triggerMode,
            'date_from' => $from->toDateString(),
            'date_to' => $to->toDateString(),
            'status' => ReportSendLog::STATUS_RUNNING,
            'triggered_by' => $user?->id,
            'started_at' => now(),
        ]);

        try {
            $generator = $this->registry->get($reportKey);

            if ($generator === null) {
                throw new \InvalidArgumentException("Report key '{$reportKey}' is not registered.");
            }

            if ($generator instanceof SplitsIntoRuns && ! $generator->isRun()) {
                return $this->sendRuns($log, $generator, $from, $to, $triggerMode, $user);
            }

            $report = $generator->generate($from, $to);
            // A run ("doc_WM022@MO123") goes to the recipients of its report ("doc_WM022").
            $recipients = ($this->resolveRecipients)(explode('@', $reportKey, 2)[0]);

            $log->row_count = $report['row_count'];
            $log->recipients_to = implode(', ', $recipients['to']);
            $log->recipients_cc = implode(', ', $recipients['cc']);

            if (($report['skip_if_empty'] ?? false) === true && (int) $report['row_count'] === 0) {
                $log->status = ReportSendLog::STATUS_SKIPPED;
                $log->error_message = $generator instanceof AutoGeneratedDocumentReport
                    ? 'No trigger material usage found for this period.'
                    : 'No records found for this period.';
                $log->completed_at = now();
            } elseif ($recipients['to'] === []) {
                $log->status = ReportSendLog::STATUS_SKIPPED;
                $log->error_message = 'No recipients resolved.';
                $log->completed_at = now();
            } else {
                $attachments = is_array($report['attachments'] ?? null)
                    ? $report['attachments']
                    : [];

                $log->save();

                SendReportEmailJob::dispatch(
                    $log->id,
                    $recipients['to'],
                    $report['subject'],
                    $report['html'],
                    $recipients['cc'],
                    $attachments,
                );

                return $log->refresh();
            }
        } catch (Throwable $e) {
            $log->status = ReportSendLog::STATUS_FAILED;
            $log->error_message = $e->getMessage();
            $log->completed_at = now();
        }

        $log->save();

        return $log;
    }

    /**
     * Sends each run (e.g. each MO's batch card) as its own report and email;
     * the parent log summarises them.
     */
    private function sendRuns(
        ReportSendLog $log,
        SplitsIntoRuns $generator,
        CarbonInterface $from,
        CarbonInterface $to,
        string $triggerMode,
        ?User $user,
    ): ReportSendLog {
        $runs = collect($generator->runKeys($from, $to))
            ->map(fn (string $runKey): ReportSendLog => $this($runKey, $from, $to, $triggerMode, $user));

        $sent = $runs->where('status', ReportSendLog::STATUS_SENT)->count();
        $failed = $runs->where('status', ReportSendLog::STATUS_FAILED)->count();

        $log->row_count = $runs->count();
        $log->status = match (true) {
            $runs->isEmpty() => ReportSendLog::STATUS_SKIPPED,
            $sent > 0 => ReportSendLog::STATUS_SENT,
            $failed > 0 => ReportSendLog::STATUS_FAILED,
            default => ReportSendLog::STATUS_SKIPPED,
        };
        $log->error_message = $runs->isEmpty()
            ? 'No MO runs found for this period.'
            : sprintf('%d run(s): %d sent, %d skipped, %d failed - see the individual run logs.', $runs->count(), $sent, $runs->count() - $sent - $failed, $failed);
        $log->completed_at = now();
        $log->save();

        return $log;
    }
}
