<?php

namespace Tests\Feature\Reporting;

use App\Domains\Reporting\ReportRegistry;
use App\Models\BatchRecord;
use App\Models\DocumentReference;
use App\Models\ManufacturingOrder;
use App\Models\Product;
use App\Models\ReportRecipient;
use App\Models\ReportSendLog;
use App\Models\WinManIssueLog;
use App\Operations\SendOffice365MailOperation;
use App\Operations\SendReportOperation;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Mockery;
use Tests\TestCase;

class AutoGeneratedDocumentReportTest extends TestCase
{
    use RefreshDatabase;

    private function fakeMailer(bool $expectSend): void
    {
        $mail = Mockery::mock(SendOffice365MailOperation::class);
        if ($expectSend) {
            $mail->shouldReceive('__invoke')->once();
        } else {
            $mail->shouldReceive('__invoke')->never();
        }
        $this->instance(SendOffice365MailOperation::class, $mail);
    }

    private function seedBatchWithIssue(string $materialCode, string $issueStatus = WinManIssueLog::STATUS_SUCCESS): BatchRecord
    {
        static $sequence = 0;
        $sequence++;

        $product = Product::create(['recipe_code' => 'R1-'.$sequence, 'product_name' => 'Test Product', 'active_flag' => true]);
        $order = ManufacturingOrder::create([
            'mo_number' => 'MO'.$sequence, 'winman_manufacturing_order' => 500 + $sequence, 'winman_manufacturing_order_id' => 'MO00'.(500 + $sequence),
            'recipe_code' => 'R1-'.$sequence, 'product_id' => $product->id, 'planned_quantity' => 100, 'quantity_outstanding' => 100,
            'winman_system_type' => 'F', 'status' => 'selected',
        ]);
        $batch = BatchRecord::create([
            'manufacturing_order_id' => $order->id, 'product_id' => $product->id, 'batch_number' => 'WM-BUCKET-'.$sequence,
            'production_date' => now()->toDateString(), 'planned_quantity' => 100,
            'status' => BatchRecord::STATUS_IN_PROGRESS,
        ]);

        WinManIssueLog::create([
            'batch_record_id' => $batch->id,
            'winman_manufacturing_order' => 500 + $sequence,
            'material_code' => $materialCode,
            'lot_number' => 'LOT-BUCKET-'.$sequence,
            'quantity_issued' => 25.5,
            'issue_user' => 'Operator One',
            'issue_date' => now(),
            'issue_status' => $issueStatus,
        ]);

        return $batch;
    }

    public function test_report_lists_matching_material_usage_and_builds_pdf(): void
    {
        DocumentReference::create([
            'code' => 'WM012',
            'title' => 'Wet Mustard Bucket Processing - 5kg',
            'module' => 'Bucket Packing',
            'trigger_material_codes' => ['90010012'],
            'status' => 'Active',
        ]);

        $matchingBatch = $this->seedBatchWithIssue('90010012');
        $this->seedBatchWithIssue('90010099'); // non-matching code
        $this->seedBatchWithIssue('90010012', WinManIssueLog::STATUS_REJECTED); // matching code but not success

        $report = app(ReportRegistry::class)->get('doc_WM012')->generate(now()->startOfDay(), now()->endOfDay());

        $this->assertSame(1, $report['row_count']);
        $this->assertTrue($report['skip_if_empty']);
        $this->assertStringContainsString((string) $matchingBatch->batch_number, $report['html']);
        $this->assertArrayHasKey('attachments', $report);
        $this->assertFileExists($report['attachments'][0]['path']);
    }

    public function test_report_skips_when_trigger_material_not_used(): void
    {
        DocumentReference::create([
            'code' => 'WM012',
            'title' => 'Wet Mustard Bucket Processing - 5kg',
            'module' => 'Bucket Packing',
            'trigger_material_codes' => ['90010012'],
            'status' => 'Active',
        ]);

        $report = app(ReportRegistry::class)->get('doc_WM012')->generate(now()->startOfDay(), now()->endOfDay());

        $this->assertSame(0, $report['row_count']);
        $this->assertTrue($report['skip_if_empty']);
        $this->assertArrayNotHasKey('attachments', $report);
    }

    public function test_registry_does_not_resolve_document_without_trigger_codes(): void
    {
        DocumentReference::create([
            'code' => 'WM014',
            'title' => 'Primary Packaging Records - Drums',
            'module' => 'Packaging Traceability',
            'status' => 'Active',
        ]);

        $this->assertFalse(app(ReportRegistry::class)->has('doc_WM014'));
        $this->assertNull(app(ReportRegistry::class)->get('doc_WM014'));
    }

    public function test_send_report_operation_skips_when_trigger_material_not_used(): void
    {
        $this->fakeMailer(expectSend: false);

        DocumentReference::create([
            'code' => 'WM012',
            'title' => 'Wet Mustard Bucket Processing - 5kg',
            'trigger_material_codes' => ['90010012'],
            'status' => 'Active',
        ]);
        ReportRecipient::create(['report_key' => null, 'recipient_type' => 'direct', 'recipient_email' => 'qa@example.com', 'is_cc' => false, 'enabled' => true]);

        $log = app(SendReportOperation::class)('doc_WM012', now()->startOfDay(), now()->endOfDay(), 'scheduled');

        $this->assertSame(ReportSendLog::STATUS_SKIPPED, $log->status);
        $this->assertStringContainsString('trigger material', (string) $log->error_message);
    }

    public function test_send_report_operation_sends_when_trigger_material_used(): void
    {
        $this->fakeMailer(expectSend: true);

        DocumentReference::create([
            'code' => 'WM012',
            'title' => 'Wet Mustard Bucket Processing - 5kg',
            'trigger_material_codes' => ['90010012'],
            'status' => 'Active',
        ]);
        $this->seedBatchWithIssue('90010012');
        ReportRecipient::create(['report_key' => null, 'recipient_type' => 'direct', 'recipient_email' => 'qa@example.com', 'is_cc' => false, 'enabled' => true]);

        $log = app(SendReportOperation::class)('doc_WM012', now()->startOfDay(), now()->endOfDay(), 'scheduled');

        $this->assertSame(ReportSendLog::STATUS_SENT, $log->status);
        $this->assertSame(1, $log->row_count);
    }

    protected function tearDown(): void
    {
        Mockery::close();
        parent::tearDown();
    }
}
