<?php

namespace App\Domains\Reporting\Reports;

use App\Domains\Reporting\Support\DocumentSources;
use App\Models\DocumentReference;
use App\Models\WinManIssueLog;
use Carbon\CarbonInterface;

/**
 * Dynamically generates an auto-triggered document (e.g. WM012, WM014) when
 * any of its configured trigger_material_codes were issued to a batch (via
 * WinMan BOM allocation) within the report period. Resolved at runtime by
 * ReportRegistry for keys of the form "doc_{code}" — one class serves every
 * document configured in Settings > Documents, no per-document subclass needed.
 */
class AutoGeneratedDocumentReport extends CalibrationSheetReport
{
    public function __construct(private readonly DocumentReference $document)
    {
    }

    public function key(): string
    {
        return 'doc_'.$this->document->code;
    }

    public function name(): string
    {
        return trim($this->document->code.' - '.$this->document->title);
    }

    public function generate(CarbonInterface $from, CarbonInterface $to): array
    {
        $rows = $this->sheetRows($from, $to);

        if ($rows === []) {
            return [
                'subject' => sprintf('DBMTS · %s (%s to %s)', $this->name(), $from->toDateString(), $to->toDateString()),
                'html' => '',
                'row_count' => 0,
                'skip_if_empty' => true,
            ];
        }

        $payload = parent::generate($from, $to);
        $payload['skip_if_empty'] = true;

        return $payload;
    }

    protected function documentCode(): string
    {
        return $this->document->code;
    }

    protected function sheetTitle(): string
    {
        return $this->document->title;
    }

    protected function sourceKey(): string
    {
        return DocumentSources::MATERIAL_TRIGGER;
    }

    protected function resolveDocument(): ?DocumentReference
    {
        return $this->document;
    }

    protected function sheetInstructions(): array
    {
        $codes = $this->triggerCodes();

        return [
            'Auto-generated because a configured trigger raw material was issued to a batch today.',
            'Trigger material code(s): '.($codes !== [] ? implode(', ', $codes) : 'none configured'),
        ];
    }

    protected function sheetRecords(CarbonInterface $from, CarbonInterface $to): iterable
    {
        $codes = $this->triggerCodes();
        if ($codes === []) {
            return [];
        }

        return WinManIssueLog::query()
            ->with(['batchRecord', 'batchIngredientLot'])
            ->where('issue_status', WinManIssueLog::STATUS_SUCCESS)
            ->whereIn('material_code', $codes)
            ->whereDate('issue_date', '>=', $from->toDateString())
            ->whereDate('issue_date', '<=', $to->toDateString())
            ->orderBy('issue_date')
            ->get();
    }

    /**
     * @return array<int, string>
     */
    private function triggerCodes(): array
    {
        return collect($this->document->trigger_material_codes ?? [])
            ->map(fn ($code): string => trim((string) $code))
            ->filter()
            ->values()
            ->all();
    }
}
